# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  trivyVersion: 0.9.1

steps:
- script: |
    sudo apt-get install rpm
    wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
    sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
    trivy -v
  displayName: 'Download and install Trivy'
- task: DockerInstaller@0
  inputs:
      dockerVersion: '17.09.0-ce'
- task: CmdLine@2
  inputs:
    script: 'docker pull java'
- task: CmdLine@2
  inputs:
      script: |
        - task: CmdLine@2
          displayName: "Run trivy scan"
          inputs:
            script: |
              trivy image java
